# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: "python-reports"
description: "Generates reports for Python team."

inputs:
  repository:
    description: "The GitHub issue repository to generate the report for."
    required: true
  prs:
    description: "The GitHub code repository to generate the report for, if different to issues."
    required: false
    default: ''
  team:
    description: "Comma-separated list of GitHub user names of the organizational contributors for this repo (including historical)."
    required: false
    default: 'vs-code-engineering,Tyriar,anthonykim1,connor4312,cwebster-99,eleanorjboyd,rzhao271,KacieKK,AdamYoblick,AlexanderSher,Anapo14,CTrando,Cameron,DavidKutu,DonJayamanne,IanMatthewHuff,JakeRadMSFT,JiayuanL,JoshuaPartlow,LittleLittleCloud,MikhailArkhipov,MinKPark,RaymonGulati1,SiddhanthUnnithan,StellaHuang95,akashraju4,amunger,anopo4,ayim,binderjoe,brettcannon,brianbok,bschnurr,claudiaregio,d3r3kk,debonte,ericsnowcurrently,erictraut,fabioz,gilbertw,gramster,greazer,gvanrossum,heejaechang,huguesv,ijoosong,int19h,jakebailey,jflam,jmew,joyceerhl,judej,karrtikr,karthiknadig,kawilkin,kieferrm,kimadeline,luabud,minsa110,paulacamargo25,qubitron,rchiodo,ronglums,savannahostrowski,sevillal,shsuman,smortaz,swinner95,tbombach,vsfeedback,weidezhong-msft,xiaofeng0123,zewditu,zhouwangyang,zooba'    
  githubTokenRead:
    description: "The Github token or PAT token (preferred) for API access to read issues."
    required: true
  githubTokenCommit:
    description: "The Github token or PAT token (preferred) for API access to commit reports."
    required: true    
  weekly:
    description: "Whether to generate a weekly report (else daily)."
    required: false
    default: false
  hotspots:
    description: "Whether to generate a report on frequently changed files."
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: Set environment
      run: |
        echo -n "TEAM='" >> $GITHUB_ENV
        echo -n ${{ inputs.team }} >> $GITHUB_ENV    
        echo "'" >> $GITHUB_ENV
        echo -n "REPO='microsoft/" >> $GITHUB_ENV
        echo -n ${{ inputs.repository }} >> $GITHUB_ENV
        echo "'" >> $GITHUB_ENV
        echo -n "PRS='" >> $GITHUB_ENV
        echo -n ${{ inputs.prs }} >> $GITHUB_ENV
        echo "'" >> $GITHUB_ENV        
      shell: bash
    - name: Generate full report
      if: inputs.weekly == 'true'
      uses: gramster/github-issue-reporter@main
      with:
        repository: ${{ env.REPO }}
        prs: ${{ env.PRS }}
        githubTokenRead: ${{ inputs.githubTokenRead }}
        githubTokenCommit: ${{ inputs.githubTokenCommit }}        
        reportNameTemplate: 'fullreport.md'
        reportPath: ${{ inputs.repository }}
        all: true
        hotspots: ${{ inputs.hotspots }}
        team: ${{ env.TEAM }}
        days: 7
    - name: Generate limited report
      if: inputs.weekly != 'true'
      uses: gramster/github-issue-reporter@main
      with:
        repository: ${{ env.REPO }}
        prs: ${{ env.PRS }}        
        githubTokenRead: ${{ inputs.githubTokenRead }}
        githubTokenCommit: ${{ inputs.githubTokenCommit }}        
        reportPath: ${{ inputs.repository }}
        hotspots: ${{ inputs.hotspots }}        
        team: ${{ env.TEAM }}
