# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: "python-reports"
description: "Generates reports for Python team."

inputs:
  repository:
    description: "The GitHub issue repository to generate the report for."
    required: true
  prs:
    description: "The GitHub code repository to generate the report for, if different to issues."
    required: false
    default: ''
  team:
    description: "Comma-separated list of GitHub user names of the core team for this repo."
    required: false
    default: ''    
  githubTokenRead:
    description: "The Github token or PAT token (preferred) for API access to read issues."
    required: true
  githubTokenCommit:
    description: "The Github token or PAT token (preferred) for API access to commit reports."
    required: true    
  weekly:
    description: "Whether to generate a weekly report (else daily)."
    required: false
    default: false
  hotspots:
    description: "Whether to generate a report on frequently changed files."
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: Set environment
      run: |
        echo -n "TEAM='" >> $GITHUB_ENV
        echo -n ${{ inputs.team }} >> $GITHUB_ENV    
        echo "'" >> $GITHUB_ENV
        echo -n "REPO='microsoft/" >> $GITHUB_ENV
        echo -n ${{ inputs.repository }} >> $GITHUB_ENV
        echo "'" >> $GITHUB_ENV
        echo -n "PRS='" >> $GITHUB_ENV
        echo -n ${{ inputs.prs }} >> $GITHUB_ENV
        echo "'" >> $GITHUB_ENV        
      shell: bash
    - name: Generate full report
      if: inputs.weekly == 'true'
      uses: gramster/github-issue-reporter@main
      with:
        repository: ${{ env.REPO }}
        prs: ${{ env.PRS }}
        githubTokenRead: ${{ inputs.githubTokenRead }}
        githubTokenCommit: ${{ inputs.githubTokenCommit }}        
        reportNameTemplate: 'fullreport.md'
        reportPath: ${{ inputs.repository }}
        all: true
        hotspots: ${{ inputs.hotspots }}
        team: ${{ env.TEAM }}
    - name: Generate limited report
      if: inputs.weekly != 'true'
      uses: gramster/github-issue-reporter@main
      with:
        repository: ${{ env.REPO }}
        prs: ${{ env.PRS }}        
        githubTokenRead: ${{ inputs.githubTokenRead }}
        githubTokenCommit: ${{ inputs.githubTokenCommit }}        
        reportPath: ${{ inputs.repository }}
        hotspots: ${{ inputs.hotspots }}        
        team: ${{ env.TEAM }}
