# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: "python-reports"
description: "Generates reports for Python team."

inputs:
  repository:
    description: "The GitHub repository to generate the report for."
    required: true
  githubToken:
    description: "The Github token or PAT token (preferred) for API access."
    required: true
  weekly:
    description: "Whether to generate a weekly report (else daily)."
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: Set environment
      run |
        echo "TEAM=fabioz,luabud,ijoosong,heejaechang,zooba,brettcannon,kieferrm,ronglums,DonJayamanne,kimadeline,int19h,gramster,qubitron,rchiodo,greazer,ericsnowcurrently,judej,paulacamargo25,bschnurr,karthiknadig,JoshuaPartlow,AdamYoblick,karrtikr,StellaHuang95" >> $GITHUB_ENV
        echo -n "REPO=microsoft/" >> $GITHUB_ENV
        echo $${inputs.repository} >> $GITHUB_ENV
      shell: bash
    - name: Generate full report
      if: inputs.weekly == 'true'
      uses: gramster/github-issue-reporter@main
      with:
        repository: env.REPO
        githubToken: ${{ inputs.githubToken }}
        reportNameTemplate: 'fullreport.md'
        reportPath: ${{ inputs.repository }}
        all: true
        team: env.TEAM
    - name: Generate limited report
      if: inputs.weekly != 'true'
      uses: gramster/github-issue-reporter@main
      with:
        repository: env.REPO
        githubToken: ${{ inputs.githubToken }}
        reportPath: ${{ inputs.repository }}
        team: env.TEAM
