name: 'Generate Weekly Full Report for debugpy'

on:
  schedule:
    - cron: 0 5 * * 1    
  workflow_dispatch:
  
permissions:
  issues: read
  contents: write

jobs:
  report:
    runs-on: ubuntu-18.04
    timeout-minutes: 10
    steps:
      - id: report
        uses: gramster/python-reports@main
        with:
          repository: 'debugpy'
          githubToken: ${{ secrets.PAT }}
          weekly: true
        
