name: 'Generate Weekly Full Report for Java Semantic Kernel'

on:
  schedule:
    - cron: 0 5 * * 1    
  workflow_dispatch:
  
permissions:
  issues: read
  contents: write

jobs:
  report:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - id: report
        uses: gramster/python-reports@main
        with:
          repository: 'semantic-kernel-java'
          githubToken: ${{ secrets.PAT }}
          weekly: true
          hotspots: true
          team: 'johnoliver,dsgrieve,milderhc,web-flow,brunoborges,markwallace-microsoft,joebraley,joe-braley,Luigi96,d3r3kk,dmytrostruk,j8-redis,yoshioterada,karianna'
          
