name: 'Generate Daily Report for jupyter'

on:
#  schedule:
#    - cron: 30 4 * * *    
  workflow_dispatch:
  
permissions:
  issues: read
  contents: write

jobs:
  report:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - id: report
        uses: gramster/python-reports@main
        with:
          repository: 'vscode-jupyter'
          githubToken: ${{ secrets.PAT }}
        
