name: 'Generate Daily Report for PTVS'

on:
  schedule:
    - cron: 30 5 * * *    
  workflow_dispatch:
  
permissions:
  issues: read
  contents: write

jobs:
  report:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - id: report
        uses: gramster/python-reports@main
        with:
          repository: 'PTVS'
          githubToken: ${{ secrets.PAT }}
        
