name: 'Generate Weekly Report for PVSC'

on:
  schedule:
    - cron: 0 3 * * 1    
  workflow_dispatch:
  
permissions:
  issues: read
  contents: write

jobs:
  report:
    runs-on: ubuntu-18.04
    timeout-minutes: 10
    steps:
      - id: report
        uses: gramster/python-reports@main
        with:
          repository: 'vscode-python'
          githubToken: ${{ secrets.PAT }}
          weekly: true
          count: 15
        
