name: 'Generate Daily Report for pylance'

on:
  schedule:
    - cron: 7 30 * * *    
  workflow_dispatch:
  
permissions:
  issues: read
  contents: write

jobs:
  report:
    runs-on: ubuntu-18.04
    timeout-minutes: 10
    steps:
      - id: report
        uses: gramster/github-issue-reporter@main
        with:
          repository: 'microsoft/pylance-release'
          githubToken: ${{ secrets.PAT }}
          reportPath: .
          team: '+savannahostrowski,luabud,ijoosong,heejaechang,zooba,brettcannon,kieferrm,ronglums,DonJayamanne,kimadeline,int19h,gramster,qubitron,rchiodo,greazer,ericsnowcurrently,judej,paulacamargo25,bschnurr,karthiknadig,JoshuaPartlow,AdamYoblick,karrtikr,StellaHuang95'
 

