name: 'Generate Daily Report for pylance'

on:
  schedule:
    - cron: 30 7 * * *    
  workflow_dispatch:
  
permissions:
  issues: read
  contents: write

jobs:
  report:
    runs-on: ubuntu-18.04
    timeout-minutes: 10
    steps:
      - id: report
        uses: gramster/python-reports@main
        with:
          repository: 'pylance-release'
          githubToken: ${{ secrets.PAT }}
        
